# -*- coding: utf-8 -*-
"""1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1_UtZZIGt2Ko7K4kRvPNflLCZ_9HCL02z
"""

import numpy as np
from skimage.measure import label, regionprops
import imageio
# Load the image and convert it to a numpy array
img = imageio.imread('image1.png')
img_array = np.array(img)

# Identify the white pixels and label them
white_pixels = (img_array == 1)
labels = label(white_pixels)

# Compute the bounding boxes of each white patch
bounding_boxes = []
for region in regionprops(labels):
    minr, minc, maxr, maxc = region.bbox
    bounding_boxes.append([minc, minr, maxc - minc, maxr - minr])

# Print the bounding boxes
print(bounding_boxes)