# -*- coding: utf-8 -*-
"""2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1_UtZZIGt2Ko7K4kRvPNflLCZ_9HCL02z
"""

pip install soundex

from collections import defaultdict
import fuzzy
def search_phonetic_combinations(search_string, file):
    # Generate all possible phonetic combinations of the search string
    phonetic_combinations = []
    for i in range(len(search_string)):
        for j in range(i, len(search_string)):
            soundex = fuzzy.Soundex(len(search_string[i:j+1]))
            phonetic_combination = soundex(search_string[i:j+1])
            if phonetic_combination not in phonetic_combinations:
                phonetic_combinations.append(phonetic_combination)

    # Open the file and search for phonetic combinations
    matching_words = []
    with open(file, 'r') as f:
        for line in f:
            for phonetic_combination in phonetic_combinations:
                if phonetic_combination in line:
                    matching_words.append(line.strip())
                    break

    return matching_words
print(search_phonetic_combinations("Murthy","/content/file.txt"))